// <auto-generated />
using System;
using GridPulse.UsageAggregation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GridPulse.UsageAggregation.Migrations
{
    [DbContext(typeof(UsageAggregationDbContext))]
    [Migration("20260912115124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GridPulse.UsageAggregation.HourlyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalKwh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MeterId", "PeriodStart")
                        .IsUnique();

                    b.ToTable("HourlyUsages");
                });

            modelBuilder.Entity("GridPulse.UsageAggregation.ProcessedReading", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Kwh")
                        .HasColumnType("double precision");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReadingId");

                    b.ToTable("ProcessedReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
